package uk.ac.cf.client1.team7sohokidschristmaslights.contactPage;

// Import the necessary annotations from Lombok
import lombok.AllArgsConstructor;
import lombok.Data;

// Mark the class as a data class using the @Data annotation
@Data
// Generate an all-args constructor using the @AllArgsConstructor annotation
@AllArgsConstructor
public class Contact {

    // Define private fields for contact information
    private Integer id;       // Unique identifier for the contact
    private String name;      // Name of the person associated with the contact
    private String email;     // Email address
    private String subject;   // Subject of the contact message
    private String message;   // Actual message content

    // Additional methods (getters, setters, equals, hashCode, toString) are automatically generated by Lombok
}